Modified markdown2pdf to check that input file exists and is readable, and error exit if not.
git-svn-id: https://pandoc.googlecode.com/svn/trunk@103 788f1e2b-df1e-0410-8736-df70ead52e1b

diff --git a/markdown2pdf b/markdown2pdf
--- a/markdown2pdf
+++ b/markdown2pdf
@@ -60,6 +60,11 @@ done
 
 infile=$1
 
+if ! [ -r $infile ]; then
+    echo >&2 "'$infile' not found"
+    exit 1
+fi
+
 if [ $# -gt 1 ]; then
     shift
     echo >&2 "Warning: extra arguments '$@' will be ignored!"
